version: "3.9"
services:
  nodejs-one:
    build: ./nodejs-one
    image: naisa/${PROJECT_NAME}_nodejs-one
    volumes:
      - ./nodejs-one:/nodejs-one
    environment:
      VERSION: ${VERSION}

  nodejs-two:
    build: ./nodejs-two
    image: naisa/${PROJECT_NAME}_nodejs-two
    volumes:
      - ./nodejs-two:/nodejs-two
    environment:
      VERSION: ${VERSION}