version: "3.9"
services:
  nodejs-one:
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      NODE_ENV: development
      NODEJS_ONE_PORT: 3000

  nodejs-two:
    ports:
      - "4000:4000"
    command: "npm run dev"
    environment:
      NODE_ENV: development
      NODEJS_TWO_PORT: 4000

  nodejs-ping:
    command: "npm run dev"
    environment:
      NODE_ENV: development